### ISSUE TITLE
Вынести все изменения в меню + список оп трейтов.

### ISSUE THREAD

**Issue by Techmind** [hadaev8/HumanFallenEmpires#2]
Можно все изменения как-то вынести в меню, чтоб можно было включать опционально новые фичи.
Я например хочу только новые трейты лидерам + собствено квесты\ивенты.

1) А можно убрать exodus (как технологию), если отключена чума  ? Я так понял она нужна, чтоб убить свою планету в каком-то эвенте связанном с чумой.

2) Можно отключить\понерфить трейт жадности (greed) - преимущество человку он дает СЛИШКОМ большое, аи не умеет рабоать с анрестом и потому не особо круто его использует (ну если только, ты его не заставишь платить трибьют), а человек просто поднимет стандарты житья и фактически получит за счет +25-50% трат consumer goods на каждого жителя +50% к минералам и энергии. Еще счастье можно поднять paradise dome, если тупо зарашить ветку гармонии.
Вобще его отключил у себя.

3) Lovable buffon - до фракций(года до 10-го) - очень херовый скилл (ну или норм скил, если выпадет с deep connections), после - тупо OP +5% ко всем ресурсам = бонусу 1-го лвла пацифиста, что очень дохера. 
Отключил, как потенциально изначальный. (initial = no)
4) human_fallen_empires_governor_trait_pious - судя по коду, тоже что "lovable buffon" , но только на все планеты в кор-секторе, тоже по сути OP.
Аналогично 3 только для сектора и без -1 инфлюенс, на само деле даже мощнее 3-его, т.к. не стоит инфлюенса. (Сделал, initial = no)

5) governor_trait_manager
-20% апкипа очень сильно, порезал себе до -10%

Edit: есть трейт "architectural_sence", который уже дает -10% и они могут появиться оба, будет 1-0.2 = 0.8 - 0.1 = 0.7, что прям совсем адово, кароч трейт либо надо выкинуть совсем, либо сделать -15%, но добавить какой-то минус типа +5% к "цене здания".

6) human_fallen_empires_governor_trait_telepath
чем отличаеся от "champion_of_people", кроме того, что дает ЕЩЕ больше бонусов ?

7) scientist_trait_thoughtful - то еще гавно, обычно обозначает, что этого чела лучше выкинуть и нанять нового (если он при исследованиях его получил), единственное исключение челы 4-5го уровня, которые смогут пройти квест на прекурсор\ливиафан.

8) scientist_trait_wary - вобще-то OP, т.к. позволяет узнать, если варги в ближайшиз системах и не исследовать их.

9) leader_potential_add - я так понимаю контролирует возможность появления, что-то типа ксенофила или лучшей работы с рабами, не должно попадаться в ксенофильной этике и соответственно демократической республике, хз можно ли это добавить

10) trait_former_fighter - бесполезен в 2.0, т.к. страйккрафт появляется хз когда вобще и вобще не сильно пярм полезен (вроде контрит 1 из кризисов чуток из-за бага в скаут-крафте), но один фиг то еще гавно.

11) trait_extramundane = OP.  считай +10 уровней к адмиралу. Даже 0.1 очень сильно будет (+3.5 уровня)

12) У генералов перки тоже оп, но они не особо решают потому можно забить.

**Comment by Techmind** [comment]
Еще как вариант разбить мод на много мелких модов, чтоб можно было чето свое собрать из кусочков (так и конфликтом поменьше).

**Comment by hadaev8** [comment]
Исход не про чуму.
Может быть.
Он дает не ко всем ресурсам. Только единство.
architectural_sence нет в ванили.
champion_of_people нет в ванили.

Ну и я не считаю, что все трейты должны быть одинаковы.
Поменял слегка lovable buffon, чтобы был более уникальным, + есть текущие не зарелизенные изменения трейтов.
И меню кастомизирует насколько это возможно.

**Comment by Techmind** [comment]
https://stellaris.paradoxwikis.com/Leader
"Architectural Sense"/" Champion of the People" - в вики они есть.
Может в файлах по другому называюся, если честно так из головы взял, не смотрел как они конкретно называются.

Edit: а стоп соврал - это у лидера, у говернора - Architectural Interest.

**Comment by Techmind** [comment]
Еще есть - Reformer | +10% monthly  unity, тоже по моему с каким-то перком пересекается, нужно чтоб они были взаимо-исключающими.

**Comment by hadaev8** [comment]
Губернатор архитектор уменьшает цену постройки, а не содержания.
