### ISSUE TITLE
Баг с отключенными пиратами.

### ISSUE THREAD

**Issue by Techmind** [hadaev8/HumanFallenEmpires#3]
Нет 10-летней задержки перед спавнами + нет проверки, что есть станция ВНЕ базовой системы.

Кароче улетаешь исследовать 1-ю же систему и натыкаешься на пиратов.

**Comment by hadaev8** [comment]
Если пираты отключены, работают ванильные, вопросы к разрабам.

**Comment by Techmind** [comment]
Ок, 10 летнего периода не нашел в коде.

Но:

```bash
cat common/on_actions/00_on_actions.txt | grep pirate -B 20 | grep -e "pirate" -e "on_" | grep -v "#"
on_yearly_pulse = {
		pirate.4
on_planet_defenders_lose = {
on_entering_system_fleet = {
		pirate.10
		pirate.25
on_fleet_auto_move_arrival = {
on_building_mining_station = {
		pirate.3
on_join_alliance = {
on_leave_alliance = {
on_country_destroyed = {
		pirate.51
on_entering_wormhole = {
on_jump_drive = {
on_pirate_spawn = {
		pirate.49
```


И смотрим события:

```bash
cat events/pirate_events.txt | grep -e "id = pirate.4" -e "id = pirate.5" -e "id = pirate.10" -B 2 -A 10 | head -n 35

event = {
	id = pirate.4
	hide_window = yes
	is_triggered_only = yes

	immediate = {
		every_country = {
			limit = {
				NOT = { has_country_flag = birth_of_piracy }
			}
			country_event = { id = pirate.5 }
		}
	}
}

#yearly pulse event
country_event = {
	id = pirate.5
	hide_window = yes
	is_triggered_only = yes

	trigger = {
		is_country_type = default
		OR = {
			has_country_flag = outer_system_mining_stations_constructed
			any_owned_planet = {
				is_homeworld = no
			}
--
# discovered pirate home system
fleet_event = {
	id = pirate.10
```
Пираты спавнятся ежегодно, но только если выпало окошко "рождение пиратов".
Пират - 10, спавн базы пиратов при входе в систему (на него пох).

Флажок "outer_system_mining_stations_constructed"  ставится  при постройке 4 майнинг станции.

**Comment by Techmind** [comment]
Вот косяк здесь "birth_of_piracy", не может стартовать до 4-х майнинг станций ( и то в начале следующего года + там еще рандом, потому я думал что нужно 10 лет), а ты его ставишь при инициализации:  

```
cat human_fallen_empires_events_init.txt
...
# main installation event
country_event = {
        id = human_fallen_empires_init.100
        is_triggered_only = yes
        hide_window = yes

        immediate = {
                if = {
                        limit = {
                                not = {
                                        has_global_flag = human_fallen_empires_installed
                                }
                        }
                        every_country = {
                                # prevent spawn vanilla pirate
                                set_country_flag = birth_of_piracy
                                set_country_flag = had_pirates_spawn
                        }

**Comment by Techmind** [comment]
Как вариант -  не менять этот флажок (завязаться на него для спавна СВОИХ пиратов, т.е. чтоб они появлялись после 3-х майнинг станций с некотрой вероятностью).

**Comment by hadaev8** [comment]
Оба флага отключают спавн ванильных пиратов,  при отключении в меню флаги удаляются и пираты спавнятся по логике ванилы.

**Comment by Techmind** [comment]
Есть какой-то способ (через консоль) проверить флаг в сейве ? У меня есть сейв начала игры , где на 1 месяце (как только я прилетел в соседнюю систему) такое прозошло.

Edit: соврал, авто-сейв уже потер его.

**Comment by Techmind** [comment]
Стоп, ты отключаешь флаги при выклчении пиратов в меню, а первый тик происходит не до загрузки меню случаем ?

**Comment by hadaev8** [comment]
Когда ты жмешь начать в стартовом эвенте

**Comment by Techmind** [comment]
Не могу найти в коде место, где флаг "birth_of_piracy" удаляется.

**Comment by Techmind** [comment]
Кароче так и есть: 

        option = {
                name = human_fallen_empires_menu.2.off
                trigger = {
                        not = {
                                has_global_flag = human_fallen_empires_disable_pirate
                        }
                }
                custom_tooltip = human_fallen_empires_menu.2.off.tooltip
                hidden_effect = {
                        set_global_flag = human_fallen_empires_disable_pirate
                        every_country = {
                                limit = {
                                        is_country_type = default
                                }
                                remove_country_flag = had_pirates_spawn
                        }
                        every_country = {
                                limit = {
                                        is_country_type = human_fallen_empires_pirate
                                }
                                every_owned_planet = {
                                        human_fallen_empires_effect_convert_to_asteroid = yes
                                }
                                destroy_country = yes
                        }
                        country_event = {
                                id = human_fallen_empires_menu.1
                        }
                }
        }


Ты убираешь флаг, который по 5 годовому таймауту позволяет пиратам спавнится снова.
Но этого таймаута нет, и потому пираты могут заспавниться очень рано.

Отредактировал коммент, скопи-пастил в 1ый раз не то.

**Comment by hadaev8** [comment]
Странно, добавил первый флаг тоже.
