### ISSUE TITLE
Вылетает игра.

### ISSUE THREAD

**Issue by Techmind** [hadaev8/HumanFallenEmpires#5]
При загрузки сейва или выходе из игры в меню вылетает игра (пытается, что задеструктить выгрузить из памяти и падает).

Как это отбедажить я - хз. Генерируется дамп, но он в виндовом формате и стелларис сам по себе собран без дебаг символов.

**Comment by Techmind** [comment]
Кароч, хз, может что-то их этого наведет тебя на мысль, где именно что-то из память криво выгружается: 
#0  0x6c666544 in ?? ()
#1  0x08a3ed28 in CSpeciesRightsModule::GetSpeciesRights(CSpecies const*, bool&) const ()
#2  0x08a3ed09 in CSpeciesRightsModule::GetSpeciesRights(CSpecies const*) const ()
#3  0x08b05680 in CHasCitizenshipTypeTrigger::ActualEvaluate(CEventScope&) const ()
#4  0x08aa556d in CTrigger::Evaluate(CEventScope&) const ()
#5  0x08aa69da in CAndTrigger::ActualEvaluate(CEventScope&) const ()
#6  0x08ac2f3b in CAnyTrigger::AnyEvaluate(CEventScope&, int&, int) const ()
#7  0x08e28020 in CAnyInScriptedListTrigger<COwnedPopListBuilder>::ActualEvaluate(CEventScope&) const ()
#8  0x08aa556d in CTrigger::Evaluate(CEventScope&) const ()
#9  0x08aa69da in CAndTrigger::ActualEvaluate(CEventScope&) const ()
#10 0x08aa556d in CTrigger::Evaluate(CEventScope&) const ()
#11 0x08ac1b75 in CContextTrigger::Evaluate(CEventScope&) const ()
#12 0x08aa69da in CAndTrigger::ActualEvaluate(CEventScope&) const ()
#13 0x08aa556d in CTrigger::Evaluate(CEventScope&) const ()
#14 0x0892d4d9 in CMandateType::CheckValid(CLeader const*, CArray<CEventScopeParameter> const&, CString*) const ()
#15 0x0892c50d in CMandate::CheckValid(CLeader const*, CString*) const ()
#16 0x08927688 in CLeader::UpdateMandate() ()
#17 0x089ab224 in CPopFaction::SetLeader(CLeader*) ()
#18 0x089aaf57 in CPopFaction::~CPopFaction() ()
#19 0x1b328208 in ?? ()
#20 0xf4242010 in ?? ()
#21 0x00000750 in ?? ()
#22 0x08931b08 in CMegaStructure::~CMegaStructure() ()
#23 0xc98880f8 in ?? ()
#24 0x1b328170 in ?? ()
#25 0xf6976a99 in ?? () from /lib/i386-linux-gnu/libc-2.23.so
#26 0x1bfb80c0 in ?? ()
#27 0x088ab02f in CGameState::~CGameState() ()
#28 0x1bfb80c0 in ?? ()
#29 0x00000000 in ?? ()

**Comment by Techmind** [comment]
Почему дестркутор мега-стркутур вызывает дестркутор популяции я вобще хз =)

**Comment by hadaev8** [comment]
Ничего не могу сказать, никогда такого не было.

**Comment by hadaev8** [comment]
Исправлен оскорей всего.
